---
# tasks file for running

- name: ensure values exists: 
  assert:
    that:
    - vm_name is deifned
    - project is deifned
    - state is deifned
    quiet: True
  
- name: create virtual machine
  kubernetes.core.k8s_json_patch:
    kind: VirtualMachine
    name: "{{ vm_name }}"
    namespace: "{{ project }}"
    patch:
    - op: replace
      patch: /spec/running
      value: "{{ state }}"
