---
- name: create secret if cloud_init_secret is present
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      type: Generic
      metadata:
        name: "{{ vm_name }}-cloud-init"
        namespace: "{{ project | lower }}"
      data:
        userdata: "{{ cloud_init_secret  | b64encode }}"
  when: cloud_init_secret is defined

- name: print network attachment template
  debug: 
    msg: "{{ lookup('template', 'vm-network-attachment-definition.yaml.j2') }}"
    verbosity: 2
  loop: "{{ network_interfaces }}"
  when: network_interfaces is defined

- name: create network attachment definition
  kubernetes.core.k8s:
    state: present
    namespace: "{{ project }}"
    template: 'vm-network-attachment-definition.yaml.j2'
  loop: "{{ network_interfaces }}"
  when: network_interfaces is defined

- name: print template for virtual machine
  debug: 
    msg: "{{ lookup('template', 'vm-template.yaml.j2') }}"
    verbosity: 2

- name: create virtual machine
  kubernetes.core.k8s:
    state: present
    namespace: "{{ project }}"
    template: 'vm-template.yaml.j2'

- name: wait
  shell: oc get vmi -o jsonpath="{.status.interfaces[?(@.interfaceName=='eth1')].ipAddress}"  -n user1 fedora-custom-network
  register: result
  retries: 30
  until: result.stdout|length > 0

