- name: Create the service 
  kubernetes.core.k8s:
    state: present
    namespace: "{{ namespace }}"
    template: 'service.yml.j2'

- name: Create the route "{{ name }}"
  kubernetes.core.k8s:
    state: present
    namespace: "{{ namespace }}"
    template: 'route.yml.j2'
