- name: Apply the Openshift Operator Subscriptions
  kubernetes.core.k8s:
    template: "{{ role_path }}/files/kubevirt-hyperconverged.yaml"
 
- name: wait for Openshift Virtualizatoin Operator to install
  shell: |
    oc get operators kubevirt-hyperconverged.openshift-cnv  -o yaml
  register: result
  until: "'install strategy completed with no errors' in result.stdout"
  retries: 30

- name: Deploy hyperconverged for Openshift Virtualizaion
  kubernetes.core.k8s:
    template: "{{ role_path }}/files/hyperconverged.yaml"

- name: Check for HCO installation
  kubernetes.core.k8s_info:
    kind: HyperConverged
    api_version: hco.kubevirt.io/v1beta1
    namespace: openshift-cnv
  register: result
  until: "result.resources[0].status.conditions is defined and result.resources[0].status.conditions|selectattr('type', 'in', 'Available')|selectattr('status', 'in', 'True')|length > 0"
  retries: 30



