- name: Apply the Openshift Operator Subscriptions
  kubernetes.core.k8s:
    template: "{{ role_path }}/files/kubevirt-hyperconverged.yaml"
  
- name: wait for Openshift Virtualizatoin Operator to install
  shell: |
    oc get operators kubevirt-hyperconverged.openshift-cnv  -o yaml
  register: result
  until: "'install strategy completed with no errors' in result.stdout"
  retries: 30


- name: Deploy hyperconverged for Openshift Virtualizaion
  kubernetes.core.k8s:
   template: "{{ role_path }}/files/hyperconverged.yaml"

# TODO: Add a wait for the install
